stages:   # Los distintos “pasos” que ejecutará nuestro pipeline
  - build




build-job:      # donde compilaremos el código
  stage: build  




  script:
    - echo "Compiling the code..."
    - javac Fibonacci.java
    - echo "Compile complete."
    - echo "Testing"
    - java Fibonacci
